## Import the Dataset and Prepare the Data

In [52]:
import pandas as pd
data = pd.read_csv('./daily-co2-per-contry-2019-2021.csv')
data.head(13)

      country        date sector      value   timestamp
0      Brazil  01/01/2019  Power   0.108768  1546272000
1       China  01/01/2019  Power  14.251000  1546272000
2   EU27 & UK  01/01/2019  Power   1.882070  1546272000
3      France  01/01/2019  Power   0.053858  1546272000
4     Germany  01/01/2019  Power   0.378323  1546272000
5       India  01/01/2019  Power   3.349630  1546272000
6       Italy  01/01/2019  Power   0.160676  1546272000
7       Japan  01/01/2019  Power   1.295800  1546272000
8         ROW  01/01/2019  Power   9.171060  1546272000
9      Russia  01/01/2019  Power   2.404910  1546272000
10      Spain  01/01/2019  Power   0.125314  1546272000
11         UK  01/01/2019  Power   0.178639  1546272000
12         US  01/01/2019  Power   3.968920  1546272000

Find distinct contries

In [53]:
areas = data.country.unique()
countries = areas[:13]
print(areas)
print(countries)
top_countries = ["China", "US", "India"]

['Brazil' 'China' 'EU27 & UK' 'France' 'Germany' 'India' 'Italy' 'Japan'
 'ROW' 'Russia' 'Spain' 'UK' 'US' 'WORLD']
['Brazil' 'China' 'EU27 & UK' 'France' 'Germany' 'India' 'Italy' 'Japan'
 'ROW' 'Russia' 'Spain' 'UK' 'US']

Find distinct sectors

In [62]:
sectors = data.sector.unique()
sectors

array(['Power', 'Industry', 'Ground Transport', 'Residential',
       'Domestic Aviation', 'International Aviation'], dtype=object)

In [55]:
# convert date to Date object
data['date'] = pd.to_datetime(data['date'])

## Some Conlcusions

Before Lockdown: [01/01/2019-01/03/2020)

After Lockdown: [01/03/2020-31/12/2021]

Calculate the mean of Carbon Emission of Ground Transportaion per conuntry before and after March 1, 2020 (as the covid situaion becomes worse and worse)

In [56]:
import seaborn as sns
import numpy as np

https://www.investopedia.com/articles/investing/092915/5-countries-produce-most-carbon-dioxide-co2.asp

**NOTE**: China might need a different time period： 1.23 - 3.25， wuhan peroid

U.S 3.19 - 8.28 (or 6.15) https://www.timeanddate.com/holidays/us/lockdown-day-1, https://www.timeanddate.com/holidays/us/last-day-of-lockdown

India: March 25 2020 - May 31

Comparison:

Before: 01/01/2019 - 01/03/2019
After: 01/03/2019 - 31/12/2019

In [57]:
test1 = {"Country": countries, "2019 Jan-Feb Mean": [
], "2020 Jan-Feb Mean": [], "Difference in Previous and Current Mean (percentage change)": []}

for country in countries:
    values_before = data[
        (data['country'] == country) 
            & (data['date'] < "2019-03-01") 
            & (data['date'] >= "2019-01-01")
            & (data['sector'] == "Ground Transport")
    ]['value']
    before = round(values_before.mean(), 2)
    test1["2019 Jan-Feb Mean"].append(before)

    values_after = data[
        (data['country'] == country)
            & (data['date'] < "2020-03-01") 
            & (data['date'] >= "2020-01-01")
            & (data['sector'] == "Ground Transport")
        ]['value']
    after = round(values_after.mean(), 2)
    test1["2020 Jan-Feb Mean"].append(after)

    abs_diff = round(after - before, 2)
    per_diff = round(abs_diff / before, 2)
    test1["Difference in Previous and Current Mean (percentage change)"].append(
        "{}({:.0%})". format(abs_diff, per_diff))

test1 = pd.DataFrame(test1)
test1

,Country,2019 Jan-Feb Mean,2020 Jan-Feb Mean,Difference in Previous and Current Mean (percentage change)
0,Brazil,0.46,0.43,-0.03(-7%)
1,China,2.53,1.76,-0.77(-30%)
2,EU27 & UK,2.38,2.39,0.01(0%)
3,France,0.31,0.31,0.0(0%)
4,Germany,0.40,0.41,0.01(2%)
5,India,0.84,0.78,-0.06(-7%)
6,Italy,0.25,0.24,-0.01(-4%)
7,Japan,0.49,0.47,-0.02(-4%)
8,ROW,6.07,5.75,-0.32(-5%)
9,Russia,0.64,0.62,-0.02(-3%)
10,Spain,0.23,0.23,0.0(0%)
11,UK,0.31,0.31,0.0(0%)
12,US,4.41,4.26,-0.15(-3%)

In [58]:
test2 = {"Country": countries, "2019 Mar-May Mean": [
], "2020 Mar-May Mean": [], "Difference in Previous and Current Mean (percentage change)": []}

for country in countries:
    values_before = data[
        (data['country'] == country)
        & (data['date'] < "2019-06-01")
        & (data['date'] >= "2019-03-01")
        & (data['sector'] == "Ground Transport")
    ]['value']
    before = round(values_before.mean(), 2)
    test2["2019 Mar-May Mean"].append(before)

    values_after = data[
        (data['country'] == country)
        & (data['date'] < "2020-06-01")
        & (data['date'] >= "2020-03-01")
        & (data['sector'] == "Ground Transport")
    ]['value']
    after = round(values_after.mean(), 2)
    test2["2020 Mar-May Mean"].append(after)

    abs_diff = round(after - before, 2)
    per_diff = round(abs_diff / before, 2)
    test2["Difference in Previous and Current Mean (percentage change)"].append(
        "{}({:.0%})". format(abs_diff, per_diff))

test2 = pd.DataFrame(test2)
test2

,Country,2019 Mar-May Mean,2020 Mar-May Mean,Difference in Previous and Current Mean (percentage change)
0,Brazil,0.47,0.36,-0.11(-23%)
1,China,2.53,2.16,-0.37(-15%)
2,EU27 & UK,2.40,2.00,-0.4(-17%)
3,France,0.32,0.24,-0.08(-25%)
4,Germany,0.41,0.38,-0.03(-7%)
5,India,0.82,0.57,-0.25(-30%)
6,Italy,0.25,0.19,-0.06(-24%)
7,Japan,0.49,0.43,-0.06(-12%)
8,ROW,6.11,4.37,-1.74(-28%)
9,Russia,0.64,0.57,-0.07(-11%)
10,Spain,0.23,0.16,-0.07(-30%)
11,UK,0.31,0.25,-0.06(-19%)
12,US,4.52,3.75,-0.77(-17%)

In [79]:
test3 = {"Country": top_countries, "2019 Lockdown Mean": [
], "2020 Lockdown Mean": [], "Difference in Previous and Current Mean (percentage change)": []}

lockdown_start_19 = {"China": "2019-01-23", "US": "2019-03-19", "India": "2019-03-25"}
lockdown_ends_19 = {"China": "2019-03-25",
                    "US": "2019-06-18", "India": "2019-05-31"}
lockdown_start_20 = {"China": "2020-01-23", "US": "2020-03-19", "India": "2020-03-25"}
lockdown_ends_20 = {"China": "2020-03-25", "US": "2020-06-18", "India": "2020-05-31"}

for country in top_countries:
    values_before = data[
        (data['country'] == country)
        & (data['date'] < lockdown_ends_19[country])
        & (data['date'] >= lockdown_start_19[country])
        & ((data['sector'] == "Ground Transport") | (data['sector'] == "Domestic Aviation") | (data['sector'] == "International Aviation"))
    ]['value']
    before = round(values_before.mean(), 2)
    test3["2019 Lockdown Mean"].append(before)

    values_after = data[
        (data['country'] == country)
        & (data['date'] < lockdown_ends_20[country])
        & (data['date'] >= lockdown_start_20[country])
        & ((data['sector'] == "Ground Transport") | (data['sector'] == "Domestic Aviation") | (data['sector'] == "International Aviation"))
    ]['value']
    
    after = round(values_after.mean(), 2)
    test3["2020 Lockdown Mean"].append(after)

    abs_diff = round(after - before, 2)
    per_diff = round(abs_diff / before, 2)
    test3["Difference in Previous and Current Mean (percentage change)"].append(
        "{}({:.0%})". format(abs_diff, per_diff))

test3 = pd.DataFrame(test3)
test3

,Country,2019 Lockdown Mean,2020 Lockdown Mean,Difference in Previous and Current Mean (percentage change)
0,China,0.93,0.61,-0.32(-34%)
1,US,1.75,1.36,-0.39(-22%)
2,India,0.29,0.18,-0.11(-38%)

In [78]:
test4 = {"Country": top_countries, "2019 pre-Lockdown Mean": [
], "2020 pre-Lockdown Mean": [], "Difference in Previous and Current Mean (percentage change)": []}

lockdown_start_19 = {"China": "2019-01-23",
                     "US": "2019-03-19", "India": "2019-03-25"}
lockdown_ends_19 = {"China": "2019-03-25",
                    "US": "2019-06-18", "India": "2019-05-31"}
lockdown_start_20 = {"China": "2020-01-23",
                     "US": "2020-03-19", "India": "2020-03-25"}
lockdown_ends_20 = {"China": "2020-03-25",
                    "US": "2020-06-18", "India": "2020-05-31"}

for country in top_countries:
    values_before = data[
        (data['country'] == country)
        & (data['date'] < lockdown_start_19[country])
        & (data['date'] >= "2019-01-01")
        & ((data['sector'] == "Ground Transport") | (data['sector'] == "Domestic Aviation") | (data['sector'] == "International Aviation"))
    ]['value']
    before = round(values_before.mean(), 2)
    test4["2019 pre-Lockdown Mean"].append(before)

    values_after = data[
        (data['country'] == country)
        & (data['date'] < lockdown_start_20[country])
        & (data['date'] >= "2020-01-01")
        & ((data['sector'] == "Ground Transport") | (data['sector'] == "Domestic Aviation") | (data['sector'] == "International Aviation"))
    ]['value']

    after = round(values_after.mean(), 2)
    test4["2020 pre-Lockdown Mean"].append(after)

    abs_diff = round(after - before, 2)
    per_diff = round(abs_diff / before, 2)
    test4["Difference in Previous and Current Mean (percentage change)"].append(
        "{}({:.0%})". format(abs_diff, per_diff))

test4 = pd.DataFrame(test4)
test4

,Country,2019 pre-Lockdown Mean,2020 pre-Lockdown Mean,Difference in Previous and Current Mean (percentage change)
0,China,0.92,0.83,-0.09(-10%)
1,US,1.70,1.61,-0.09(-5%)
2,India,0.29,0.26,-0.03(-10%)

In [73]:
for country in top_countries:
    overall_value = data[(data['country'] == country)]['value'].sum()
    for sector in sectors:
        sector_value = data[(data['country'] == country) & (data['sector'] == sector)]['value'].sum()
        percentage = round(sector_value / overall_value, 2)
        print(country, sector, percentage)

China Power 0.44
China Industry 0.4
China Ground Transport 0.08
China Residential 0.07
China Domestic Aviation 0.01
China International Aviation 0.0
US Power 0.31
US Industry 0.2
US Ground Transport 0.32
US Residential 0.12
US Domestic Aviation 0.03
US International Aviation 0.01
India Power 0.5
India Industry 0.3
India Ground Transport 0.11
India Residential 0.08
India Domestic Aviation 0.0
India International Aviation 0.0